name: Release

on:
push:
tags:
  - 'v*'

jobs:
release:
permissions:
  contents: write
strategy:
  fail-fast: false
  matrix:
    include:
      - platform: 'windows-latest'
        args: ''

runs-on: ${{ matrix.platform }}
steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      node-version: lts/*
      cache: 'npm'

  - name: Install Rust stable
    uses: dtolnay/rust-toolchain@stable
    with:
      targets: x86_64-pc-windows-msvc

  - name: Install dependencies
    run: npm ci

  - name: Build and Sign Tauri App
    uses: tauri-apps/tauri-action@v0
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
    with:
      tagName: __VERSION__
      releaseName: 'krushr v__VERSION__'
      releaseBody: 'See the assets below to download the latest release.'
      releaseDraft: false
      prerelease: false
